name: "redis-cluster"
services:
  redis-cluster-setup:
    container_name: redis-cluster-setup
    image: redis:${VERSION_REDIS}
    command: >
      bash -c '
        echo "Waiting for redis nodes availability";
        sleep 10;
        for no in `seq 1 6`; do
          until redis-cli -h redis-cluster-node-0$${no} -p $$((6378 + no)) ping | grep -q "PONG"; do sleep 5; done;
          echo "Node [redis-cluster-node-0$${no}] is available";
        done
        echo "Setup redis cluster";
        redis-cli --cluster create redis-cluster-node-01:6379 redis-cluster-node-02:6380 redis-cluster-node-03:6381 redis-cluster-node-04:6382 redis-cluster-node-05:6383 redis-cluster-node-06:6384 --cluster-replicas 1 --cluster-yes
        until redis-cli -h redis-cluster-node-01 -p 6379 -c cluster info | grep -q "cluster_state:ok"; do sleep 5; done; 
        echo "All Done!";
      '
    volumes:
      - ./volumes/redis-cluster-setup:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h redis-cluster-node-01 -p 6379 -c cluster info | grep -q \"cluster_state:ok\";"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - development-network
    depends_on:
      - redis-cluster-node-01
      - redis-cluster-node-02 
      - redis-cluster-node-03
      - redis-cluster-node-04
      - redis-cluster-node-05
      - redis-cluster-node-06     
  
  redis-cluster-node-01:
    container_name: redis-cluster-node-01
    image: redis:${VERSION_REDIS}
    volumes:
      - ./redis-cluster-node-01.conf:/redis.conf
      - ./volumes/redis-cluster-node-01/data:/data
    command: redis-server /redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q 'PONG'"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - development-network
    ports:
      - "6379:6379"
      - "16379:16379"
  
  redis-cluster-node-02:
    container_name: redis-cluster-node-02
    image: redis:${VERSION_REDIS}
    volumes:
      - ./redis-cluster-node-02.conf:/redis.conf
      - ./volumes/redis-cluster-node-02/data:/data
    command: redis-server /redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q 'PONG'"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - development-network
    ports:
      - "6380:6380"
      - "16380:16380"

  redis-cluster-node-03:
    container_name: redis-cluster-node-03
    image: redis:${VERSION_REDIS}
    volumes:
      - ./redis-cluster-node-03.conf:/redis.conf
      - ./volumes/redis-cluster-node-03/data:/data
    command: redis-server /redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q 'PONG'"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - development-network
    ports:
      - "6381:6381"
      - "16381:16381"
  
  redis-cluster-node-04:
    container_name: redis-cluster-node-04
    image: redis:${VERSION_REDIS}
    volumes:
      - ./redis-cluster-node-04.conf:/redis.conf
      - ./volumes/redis-cluster-node-04/data:/data
    command: redis-server /redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q 'PONG'"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - development-network
    ports:
      - "6382:6382"
      - "16382:16382"

  redis-cluster-node-05:
    container_name: redis-cluster-node-05
    image: redis:${VERSION_REDIS}
    volumes:
      - ./redis-cluster-node-05.conf:/redis.conf
      - ./volumes/redis-cluster-node-05/data:/data
    command: redis-server /redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q 'PONG'"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - development-network
    ports:
      - "6383:6383"
      - "16383:16383"

  redis-cluster-node-06:
    container_name: redis-cluster-node-06
    image: redis:${VERSION_REDIS}
    volumes:
      - ./redis-cluster-node-06.conf:/redis.conf
      - ./volumes/redis-cluster-node-06/data:/data
    command: redis-server /redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q 'PONG'"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - development-network
    ports:
      - "6384:6384"
      - "16384:16384"

  # redisinsight:
  #   container_name: redisinsight
  #   image: redislabs/redisinsight:1.14.0
  #   ports:
  #     - 8001:8001
  #   volumes:
  #     - ./volumes/redisinsight:/db
  #   depends_on:
  #     - redis-cluster-setup
  #   networks:
  #     - development-network
  
networks:
  development-network:
    external: true
