version: "3.9"
name: "activemq"
services:
  activemq:
    container_name: activemq
    image: apache/activemq-classic:5.17.6
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
      - "61613:61613"
      - "1883:1883"
      - "61614:61614"
      - "1099:1099"
    networks:
      - development-network


networks:
  development-network:
    external: true