version: "3.9"
name: "nginx"
services:
  nginx:
    container_name: nginx
    image: nginx:1.22.1
    volumes:
      - ./dhparam.pem:/keys/dhparam.pem
      - ./nginx-server.key:/keys/nginx-server.key
      - ./nginx-server.crt:/keys/nginx-server.crt
      - ./ssl.conf:/etc/nginx/conf.d/ssl.conf
    ports:
      - "8080:80"
      - "8443:443"
