version: "3.9"
name: "nacos-cluster"
services:
  nacos-cluster-node-01:
    container_name: nacos-cluster-node-01
    image: nacos/nacos-server:${VERSION_NACOS}
    env_file:
      - ./nacos.env
    volumes:
      - nacos-cluster-node-01:/home/nacos/logs
    networks:
      nacos-cluster:
        ipv4_address: 172.16.0.11
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8848/nacos"]
      interval: 1s
      timeout: 5s
      retries: 10
    depends_on:
      nacos-cluster-mysql:
        condition: service_healthy
  
  nacos-cluster-node-02:
    container_name: nacos-cluster-node-02
    image: nacos/nacos-server:${VERSION_NACOS}
    env_file:
      - ./nacos.env
    volumes:
      - nacos-cluster-node-02:/home/nacos/logs
    networks:
      nacos-cluster:
        ipv4_address: 172.16.0.12
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8848/nacos"]
      interval: 1s
      timeout: 5s
      retries: 10
    depends_on:
      nacos-cluster-mysql:
        condition: service_healthy

  nacos-cluster-node-03:
    container_name: nacos-cluster-node-03
    image: nacos/nacos-server:${VERSION_NACOS}
    env_file:
      - ./nacos.env
    volumes:
      - nacos-cluster-node-03:/home/nacos/logs
    networks:
      nacos-cluster:
        ipv4_address: 172.16.0.13
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8848/nacos"]
      interval: 1s
      timeout: 5s
      retries: 10
    depends_on:
      nacos-cluster-mysql:
        condition: service_healthy

  nacos-cluster-mysql:
    container_name: nacos-cluster-mysql
    image: mysql:${VERSION_MYSQL}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/nacos-mysql.sql
      - nacos-cluster-mysql:/var/lib/mysql  
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nacos
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    networks:
      nacos-cluster:
        ipv4_address: 172.16.0.10
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  nacos-cluster-nginx:
    container_name: nacos-cluster-nginx
    image: nginx:1.22.1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      nacos-cluster:
        ipv4_address: 172.16.0.14
    ports:
      - 8848:80
    depends_on:
      - nacos-cluster-node-01
      - nacos-cluster-node-02
      - nacos-cluster-node-03

volumes:
  nacos-cluster-mysql:
    name: nacos-cluster-mysql
    driver: local
  nacos-cluster-node-01:
    name: nacos-cluster-node-01
    driver: local
  nacos-cluster-node-02:
    name: nacos-cluster-node-02
    driver: local
  nacos-cluster-node-03:
    name: nacos-cluster-node-03
    driver: local

networks:
  nacos-cluster:
    name: nacos-cluster
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24