name: elasticsearch-standalone
services:
  elasticsearch-standalone:
    container_name: elasticsearch-standalone
    image: elasticsearch:${VERSION_ELASTICSEARCH}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  elasticsearch-standalone-kibana:
    container_name: elasticsearch-standalone-kibana
    image: kibana:${VERSION_ELASTICSEARCH}
    ports:
      - "5601:5601"
