version: '3.9'
name: kong
services:
  kong-database:
    container_name: kong-database
    image: postgres:${VERSION_POSTGRES}
    user: postgres
    networks:
      - kong
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:5432/${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  kong-migration:
    image: kong:${VERSION_KONG}
    container_name: kong-migration
    networks:
      - kong
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=${POSTGRES_USER}
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD}
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    command: kong migrations bootstrap
  kong:
    container_name: kong
    image: kong:${VERSION_KONG}
    networks:
      - kong
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=${POSTGRES_USER}
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD}
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_completed_successfully
  konga:
    container_name: konga
    image: pantsel/konga:${VERSION_KONGA}
    networks:
      - kong
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - TOKEN_SECRET=123456
    depends_on:
      - kong
networks:
  kong:
    name: kong
    driver: bridge