version: "3.9"
name: postgres
services:
  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      postgres-network:
        ipv4_address: 192.168.166.2
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgresql://postgres:${POSTGRES_PASSWORD}@127.0.0.1:5432/postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    name: postgres
    driver: local
networks:
  postgres-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.166.0/24